server:
  port: 9090
  ssl:
    key-store: classpath:4769340_www.zhuhaiaed.xyz.pfx
    key-store-password: OwsRwh0v

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.24.43.70:3306/springboot_test_db?useAffectedRows=true&characterEncoding=utf-8
    username: admin
    password: 123456@admin
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bnuz.aed.model

#Show sql语句
logging:
  level:
    com:
      bnuz:
        aed:
          mapper: debug

auth:
  manager:
    - hello
    - getAllUsers
    - getAllManagers
    - getAllInspectors
    - createUserByMini
    - createUserByWeb
    - updateUser
    - deleteUser
    - getAllInfos
    - getAllKnows
    - getInfoOrKnow
    - addInfoOrKnow
    - updateInfoOrKnow
    - deleteInfoOrKnow
    - getFeedbacksByUserId
    - getAllFeedbacks
    - getFeedbacksCount
    - getFeedbackResultsCount
    - addFeedback
    - addFeedbackResult
    - deleteFeedback
    - deleteFeedbackResult
    - getCollectionsById
    - addCollection
    - deleteCollection
    - getAllAudits
    - getAuditsByUserId
    - getAuditById
    - addAudit
    - addAuditResult
    - updateAudit
    - updateAuditResult
    - deleteAudit
    - deleteAuditResult
    - deleteMaterial
    - getAllRecords
    - getRecordsByEquipmentId
    - getRecordsByInspectorId
    - getRecordByRecordId
    - addRecord
    - updateRecord
    - deleteRecord
    - addPosition
    - updatePosition
    - deletePosition
    - getAllEquipments
    - getEquipmentById
    - addEquipment
    - updateEquipment
    - deleteEquipment
  inspector:
    - hello
    - getInspector
    - createUserByMini
    - createUserByWeb
    - updateUser
    - getAllInfos
    - getAllKnows
    - getInfoOrKnow
    - getFeedbacksByUserId
    - addFeedback
    - deleteFeedback
    - getCollectionsById
    - addCollection
    - deleteCollection
    - getAuditsByUserId
    - getAuditById
    - addAudit
    - updateAudit
    - deleteAudit
    - deleteMaterial
    - getAllRecords
    - getRecordsByEquipmentId
    - getRecordsByInspectorId
    - getRecordByRecordId
    - addRecord
    - updateRecord
    - deleteRecord
    - getAllEquipments
    - getEquipmentById
  user:
    - hello
    - createUserByMini
    - createUserByWeb
    - updateUser
    - getAllInfos
    - getAllKnows
    - getInfoOrKnow
    - getFeedbacksByUserId
    - addFeedback
    - deleteFeedback
    - getCollectionsById
    - addCollection
    - deleteCollection
    - getAuditsByUserId
    - getAuditById
    - addAudit
    - updateAudit
    - deleteAudit
    - deleteMaterial
    - getAllEquipments
    - getEquipmentById
